### ISSUE TITLE
Why can't I run more than 20 epochs?

### ISSUE THREAD

**Issue by FuugaMo** [qiuzx2/CIBHash#7]
My input to terminal: python main.py cifar16 --train --dataset cifar10 --encode_length 16 --cuda

outcome:
...
End of epoch  17 | loss   4.1839  | contra_loss   4.1827  | kl_loss   1.2010
End of epoch  18 | loss   4.1784  | contra_loss   4.1772  | kl_loss   1.2075
End of epoch  19 | loss   4.1564  | contra_loss   4.1543  | kl_loss   2.1201
End of epoch  20 | loss   4.1070  | contra_loss   4.1043  | kl_loss   2.6907
evaluating...
 | val perf   0.1064            *Best model so far, deep copying*
Stopping epoch because loss is NaN
Stopping training session because loss is NaN
----New best   0.1064, saving
...

Every time after it automatically evaluated val perf, epoch would be stopped because loss is NaN, is it some sort of manually early stop strategy that I am not aware of? Or is there any params I am missing?

**Comment by FuugaMo** [comment]
After the first evaluation, updating the hyperparameters caused some batches to experience gradient explosion. My dataset is from the CIFAR-10 official website. Do you do any processing on the dataset?

**Comment by zexuanqiu** [comment]
Hi,
I use the CIFAR-10 official data and the processing code is the same as that of the repo. I remember that the NaN problem did not happen in all the datasets after 20 epochs when I ran the code.

**Comment by FuugaMo** [comment]
Thank you for your answer! I am still working on this problem and now I noticed that every time after evaluating, NaN problem will stably occur in the next epoch. ;(

**Comment by FuugaMo** [comment]
It turns out that this problem is caused by **lack of GPU memory and some kind of unknown bug in some previous CUDA versions?**

I have tried:
- Setting Learning Rate to 0: Did not solve the issue.
- Switching to CPU Execution: Loss explosion issue did not occur on CPU, but it was tooooo slow.
- Modifying forward Function Code: Followed your code modification, but problem persisted.
- Upgrading PyTorch and Related Libraries: Tried upgrading to versions with 'cuda' suffix (from Torch ==1.4.0 to Torch==1.5.0+cuda102), but loss explosion occurred earlier (before eval, in the first epoch).
- Downgrading CUDA Version: Attempted downgrade to CUDA 9.2, encountered new errors. Since my GPU 3070-8G's compute capability  is 8.5 but CUDA 9.2 only support it in the range 3-7.
- Changing Data Type Precision to float64: Consumed excessive memory, necessitating reduction of batch size to 16.
Decreasing Batch Size: Set batch size to 2, mitigated the problem, but it hardly improve the model after evaluating. A batch size of 4 leads to the loss NaN problem.
- Migrating to Alternative Environment: Shifted to a Colab environment, indicating a possible issue with GPU memory constraints.
- Upgrading CUDA Version to 11.1: Upgraded to a newer CUDA version, encountered MemoryError.

Here's some information of difference performance on different GPUs that I have gathered or tried:

My Machine:
- GPU: NVIDIA GeForce RTX 3070 8G
- CUDA Version:
    - Known NaN issues occurred with CUDA 10.1; 
    - Compute capability compatibility problem in CUDA 9.2;
    - MemoryError problem in CUDA 11.1; 

2080Ti Machine:
- GPU: 8 NVIDIA GeForce RTX 2080 Ti (11GB perhaps?)
- CUDA Version: 10.2
- Driver Version: 440.33.01
- Success, no NaN problem.

Colab Environment:
- GPU: NVIDIA T4 (Tesla T4)
- VRAM: 15GB
- CUDA Version: 12+
- The graph in Colab shows that the model occupied 9.2GB of all GPU RAM.
- Success, no NaN problem.

A40 GPU Environment:
- GPU: NVIDIA A40
- VRAM: Not specified
- CUDA Version: Not specified, but known to work fine in this environment.
- Success, no NaN problem.

In conclusion, I suspect that the MemoryError issue was not properly handled in older versions of CUDA, as reported in https://github.com/ultralytics/ultralytics/issues/5294: CUDA errors like "out of memory" may also lead to NaN results.

My suspicion is that older versions of CUDA may lack a proper error handling mechanism for NaN caused by insufficient memory, however, I have too few evidence of this problem. If anyone knows more specific detail of this problem, please contact me!
